Vladyslav\Bundle\BooksBundle\Entity\User:
    type: entity
    table: null
    repositoryClass: Vladyslav\Bundle\BooksBundle\Entity\UserRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: '25'
        password:
            type: string
            length: '50'
        role:
            type: string
            length: '25'
    oneToMany:
            orders:
                targetEntity:  Vladyslav\Bundle\BooksBundle\Entity\Orders
                mappedBy: user
    lifecycleCallbacks: {  }
